### ISSUE TITLE
Find the causality between sentiment index and bitcoin market returns

### ISSUE THREAD

**Issue by zackdilan** [dang-trung/crypto-sentiment-index#2]
Hello Dang, 
First of all, a great project and idea proposed have a lot of scopes. In search of that, I would like to get an acceptable correlation between bitcoin market return and sentiment index

To be more precise, we have found the relation of sentiment index on a composite market return instead of that I need with bitcoin.

okay, so  this is how I want to approach it

1. GAther the crix data only for bitcoin
2. follow the procedures with the crix_bitcoin data

![image](https://user-images.githubusercontent.com/50382476/116987709-ad432a80-accf-11eb-96af-1152efa5c766.png)

I m not able to under the _n_ in the above equation. 

PLease provide a suggestion on my idea and above question

Thanks in advance

**Comment by zackdilan** [comment]
okay, I believe they are the number of coins taking part in the calculation. Correct me if i m wrong

**Comment by dang-trung** [comment]
Hey mate,

In case you want to find causality between the sentiment index and Bitcoin returns, you can simply use Bitcoin historical data for the dependent variable. For the sentiment index, if your purpose is solely Bitcoin, I suggest you only pull social messages only related to Bitcoin (from StockTwits or Reddit) to create the index. I also suggest you use more complicated models than random forests (e.g. XGBoost, RNNs, etc.) to find the patterns (I was forced to use RF as it's my university project.)

On part of the CRIX, I'm not sure what you mean here but CRIX is just a market-cap-weighted index for the entire crypto market (because I wanted to do my analysis on the market scale). Put it simply, CRIX is like S&P500 for the US stock market or DAX30 for the German one. This index is created by a German professor named Härdle, you can read more about it here: https://thecrix.de/.

Hope this helps, cheers!

**Comment by zackdilan** [comment]
Hey thanks, 
Yes, I agree with the first point on getting bitcoin historical data and trying complex algorithms. But what would you say, will it be a better idea to use the market return based on the bitcoin market capitalization instead of CRIX(saying, it's an index for the entire market).

My final aim is to predict signal for the bitcoin trading.

**Comment by dang-trung** [comment]
If you want to predict Bitcoin directions, it's always a better idea to try Bitcoin prices or returns (if you are using models that require stationarity) as the dependent variable. Although it's true that CRIX is highly correlated with BTC (as most of the time, the crypto market moves together with Bitcoin), they're not perfectly correlated. 

In any case, as with a majority of ML problems, I believe the best solution is to just try both by yourself and see what works better, depending on the metrics you're using.

Cheers.

**Comment by zackdilan** [comment]
Hello again!

I have few questions ( for a sanity check)!

1.  How to find the Bitcoin market return series?
 i was using this equation `RM_t = Bitcoin_MarketCap_t - Bitcoin_MarketCap_t-1 / Bitcoin_MarketCap_t` . Is this right?

2. What did you mean by models that require stationarity?
   ---> Suppose if I want to use a Random forest regressor to fit a model on the basis of sentiment data features and Bitcoin prices as the dependent variable, Do I want to do some preprocessing on the data? Since the features and bitcoin prices are non-stationary right?

3. What evaluation metrics can be used in the above case?
  The MSE is enough?


Thanks in advance!

**Comment by dang-trung** [comment]
Hi Zack,

For your questions:
1. BTC returns should be calculated using Price, not Market Cap (and it's only Returns, not Market Returns). So:
	`R_t = ( BTC_Price_t - BTC_Price_(t-1) ) / BTC_Price_(t-1)`

2. Regarding stationarity, to my knowledge, only some old-school time-series models, say ARIMA or VAR, requires this. So with random forests, it doesn't matter if you do preprocessing or not.

3. On evaluation metrics, I suppose that it depends on your needs. For example, to me, when I build a model to predict returns, my ultimate goal is to generate a trading strategy that outperforms simple holding. Therefore, in this case, I choose the evaluation metric as the returns of the trading strategy that use signals generated by my model predictions. 
Tbh, MSE would do fine as well since it's likely that when your model predictions are closer to the real values, your strategy returns are better at the same time.

Hope this helps.

**Comment by zackdilan** [comment]
Thanks mate, 

That a lot of information I could have asked for. I will keep you in the loop with my advancements.

Best

**Comment by dang-trung** [comment]
Good luck with your work!
